(cl:in-package get_vrdk_pose-msg)
(cl:export '(ESTCRNTARCAMPOSE-VAL
          ESTCRNTARCAMPOSE
          CRNTARCAMPOSE-VAL
          CRNTARCAMPOSE
          ESTCRNTARODOMPOSE-VAL
          ESTCRNTARODOMPOSE
          CRNTARODOMPOSE-VAL
          CRNTARODOMPOSE
          ESTCRNTCAMODOMPOSE-VAL
          ESTCRNTCAMODOMPOSE
          CRNTCAMODOMPOSE-VAL
          CRNTCAMODOMPOSE
))