// Generated by gencpp from file get_vrdk_pose/VdrkPose.msg
// DO NOT EDIT!


#ifndef GET_VRDK_POSE_MESSAGE_VDRKPOSE_H
#define GET_VRDK_POSE_MESSAGE_VDRKPOSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/PoseStamped.h>
#include <geometry_msgs/PoseStamped.h>
#include <geometry_msgs/PoseStamped.h>
#include <geometry_msgs/PoseStamped.h>
#include <geometry_msgs/PoseStamped.h>
#include <geometry_msgs/PoseStamped.h>

namespace get_vrdk_pose
{
template <class ContainerAllocator>
struct VdrkPose_
{
  typedef VdrkPose_<ContainerAllocator> Type;

  VdrkPose_()
    : estCrntArCamPose()
    , crntArCamPose()
    , estCrntArOdomPose()
    , crntArOdomPose()
    , estCrntCamOdomPose()
    , crntCamOdomPose()  {
    }
  VdrkPose_(const ContainerAllocator& _alloc)
    : estCrntArCamPose(_alloc)
    , crntArCamPose(_alloc)
    , estCrntArOdomPose(_alloc)
    , crntArOdomPose(_alloc)
    , estCrntCamOdomPose(_alloc)
    , crntCamOdomPose(_alloc)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::PoseStamped_<ContainerAllocator>  _estCrntArCamPose_type;
  _estCrntArCamPose_type estCrntArCamPose;

   typedef  ::geometry_msgs::PoseStamped_<ContainerAllocator>  _crntArCamPose_type;
  _crntArCamPose_type crntArCamPose;

   typedef  ::geometry_msgs::PoseStamped_<ContainerAllocator>  _estCrntArOdomPose_type;
  _estCrntArOdomPose_type estCrntArOdomPose;

   typedef  ::geometry_msgs::PoseStamped_<ContainerAllocator>  _crntArOdomPose_type;
  _crntArOdomPose_type crntArOdomPose;

   typedef  ::geometry_msgs::PoseStamped_<ContainerAllocator>  _estCrntCamOdomPose_type;
  _estCrntCamOdomPose_type estCrntCamOdomPose;

   typedef  ::geometry_msgs::PoseStamped_<ContainerAllocator>  _crntCamOdomPose_type;
  _crntCamOdomPose_type crntCamOdomPose;





  typedef boost::shared_ptr< ::get_vrdk_pose::VdrkPose_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::get_vrdk_pose::VdrkPose_<ContainerAllocator> const> ConstPtr;

}; // struct VdrkPose_

typedef ::get_vrdk_pose::VdrkPose_<std::allocator<void> > VdrkPose;

typedef boost::shared_ptr< ::get_vrdk_pose::VdrkPose > VdrkPosePtr;
typedef boost::shared_ptr< ::get_vrdk_pose::VdrkPose const> VdrkPoseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::get_vrdk_pose::VdrkPose_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::get_vrdk_pose::VdrkPose_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::get_vrdk_pose::VdrkPose_<ContainerAllocator1> & lhs, const ::get_vrdk_pose::VdrkPose_<ContainerAllocator2> & rhs)
{
  return lhs.estCrntArCamPose == rhs.estCrntArCamPose &&
    lhs.crntArCamPose == rhs.crntArCamPose &&
    lhs.estCrntArOdomPose == rhs.estCrntArOdomPose &&
    lhs.crntArOdomPose == rhs.crntArOdomPose &&
    lhs.estCrntCamOdomPose == rhs.estCrntCamOdomPose &&
    lhs.crntCamOdomPose == rhs.crntCamOdomPose;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::get_vrdk_pose::VdrkPose_<ContainerAllocator1> & lhs, const ::get_vrdk_pose::VdrkPose_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace get_vrdk_pose

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::get_vrdk_pose::VdrkPose_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::get_vrdk_pose::VdrkPose_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::get_vrdk_pose::VdrkPose_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::get_vrdk_pose::VdrkPose_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::get_vrdk_pose::VdrkPose_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::get_vrdk_pose::VdrkPose_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::get_vrdk_pose::VdrkPose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "eeb9d5dc14ded266a7d01590b32d6108";
  }

  static const char* value(const ::get_vrdk_pose::VdrkPose_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xeeb9d5dc14ded266ULL;
  static const uint64_t static_value2 = 0xa7d01590b32d6108ULL;
};

template<class ContainerAllocator>
struct DataType< ::get_vrdk_pose::VdrkPose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "get_vrdk_pose/VdrkPose";
  }

  static const char* value(const ::get_vrdk_pose::VdrkPose_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::get_vrdk_pose::VdrkPose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/PoseStamped estCrntArCamPose\n"
"geometry_msgs/PoseStamped crntArCamPose\n"
"geometry_msgs/PoseStamped estCrntArOdomPose\n"
"geometry_msgs/PoseStamped crntArOdomPose\n"
"geometry_msgs/PoseStamped estCrntCamOdomPose\n"
"geometry_msgs/PoseStamped crntCamOdomPose\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/PoseStamped\n"
"# A Pose with reference coordinate frame and timestamp\n"
"Header header\n"
"Pose pose\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::get_vrdk_pose::VdrkPose_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::get_vrdk_pose::VdrkPose_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.estCrntArCamPose);
      stream.next(m.crntArCamPose);
      stream.next(m.estCrntArOdomPose);
      stream.next(m.crntArOdomPose);
      stream.next(m.estCrntCamOdomPose);
      stream.next(m.crntCamOdomPose);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct VdrkPose_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::get_vrdk_pose::VdrkPose_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::get_vrdk_pose::VdrkPose_<ContainerAllocator>& v)
  {
    s << indent << "estCrntArCamPose: ";
    s << std::endl;
    Printer< ::geometry_msgs::PoseStamped_<ContainerAllocator> >::stream(s, indent + "  ", v.estCrntArCamPose);
    s << indent << "crntArCamPose: ";
    s << std::endl;
    Printer< ::geometry_msgs::PoseStamped_<ContainerAllocator> >::stream(s, indent + "  ", v.crntArCamPose);
    s << indent << "estCrntArOdomPose: ";
    s << std::endl;
    Printer< ::geometry_msgs::PoseStamped_<ContainerAllocator> >::stream(s, indent + "  ", v.estCrntArOdomPose);
    s << indent << "crntArOdomPose: ";
    s << std::endl;
    Printer< ::geometry_msgs::PoseStamped_<ContainerAllocator> >::stream(s, indent + "  ", v.crntArOdomPose);
    s << indent << "estCrntCamOdomPose: ";
    s << std::endl;
    Printer< ::geometry_msgs::PoseStamped_<ContainerAllocator> >::stream(s, indent + "  ", v.estCrntCamOdomPose);
    s << indent << "crntCamOdomPose: ";
    s << std::endl;
    Printer< ::geometry_msgs::PoseStamped_<ContainerAllocator> >::stream(s, indent + "  ", v.crntCamOdomPose);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GET_VRDK_POSE_MESSAGE_VDRKPOSE_H
